# Generated by Django 3.2.4 on 2021-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20210629_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='thumbnail',
            field=models.ImageField(default='skjj', upload_to=''),
            preserve_default=False,
        ),
    ]
