# Generated by Django 3.2.4 on 2021-06-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_uploadfile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='location',
            field=models.CharField(default='uk', max_length=100),
            preserve_default=False,
        ),
    ]
